Implementando mongo
TACS-Grupo-X-Tic-Tacs/app-de-futbol pull request #4
Opened 2022-10-16 17:48 UTC by tfloxolodeiro

2022-10-16 17:49 UTC, Lautarourtiaga requested changes
https://youtu.be/W-N5Konsyh8

2022-10-16 17:50 UTC, tfloxolodeiro commented on apiRest/src/endpoints/app/app.module.ts
> -  imports: [PartidosModule, EstadisticasModule],
Async para que espere a que se cargue dotenv

2022-10-16 17:50 UTC, tfloxolodeiro commented on apiRest/src/endpoints/partidos/partidos.schema.ts
> +
Se podria usar el _id de mongo en vez de usar uno hecho por nosotros.

2022-10-16 17:50 UTC, tfloxolodeiro commented on botTelegram/src/comandos/comandoInscripcionPartido.ts
> +  })
No se estaba catcheando el error.

2022-10-16 17:50 UTC, tfloxolodeiro commented on botTelegram/src/main.ts
>  bootstrap();
Pasarle el repo y usarlo como lo hacen los otros comandos.

2022-10-16 17:52 UTC, tfloxolodeiro commented on botTelegram/src/main.ts
Pasarle el repo a estos comandos y usarlos como en los otros comandos, en vez de pasarle la api url.

2022-10-16 17:52 UTC, tfloxolodeiro commented on botTelegram/src/comandos/comandoInscripcionPartido.ts
>  };
No se estaba catcheando el error, explotaba si superaba los 12 jugadores.

2022-10-16 17:53 UTC, Lautarourtiaga commented on botTelegram/src/comandos/comandoInscripcionPartido.ts
>  };
Habría que agregar un test

2022-10-16 17:54 UTC, tfloxolodeiro commented
Respecto al casco de diamante @Lautarourtiaga , me parece que seria caro pero veo los beneficios.

2022-10-16 17:56 UTC, Lautarourtiaga commented
Yo me encargo del dockerino y los tests

2022-10-16 17:56 UTC, Lautarourtiaga commented
Respecto al casco de diamante, fíjate

2022-10-16 18:07 UTC, tfloxolodeiro commented on botTelegram/src/comandos/comandoInscripcionPartido.ts
>  };
no se que es eso

2022-10-16 18:08 UTC, Lautarourtiaga commented on botTelegram/src/comandos/comandoInscripcionPartido.ts
>  };
??

2022-10-16 23:09 UTC, Lautarourtiaga commented on botTelegram/src/main.ts
a quien le hablas ??

2022-10-16 23:09 UTC, Lautarourtiaga requested changes
hola este es un medio de comunicación como reddit y myspace y facebook no ??

HOLAAA

2022-10-16 23:16 UTC, Lautarourtiaga requested changes
gracias por todo el laburo!!!!1

2022-10-16 23:19 UTC, tfloxolodeiro commented
hola amigos hoy empece a ver utena

2022-10-16 23:33 UTC, tfloxolodeiro commented
Mira ahi esta utena (la de la derecha) 
![image](https://user-images.githubusercontent.com/37090248/196064073-d5c9bb9a-a070-46fa-97a1-c069d94e30fd.png)

2022-10-16 23:37 UTC, tfloxolodeiro commented
voy a dejar la carrera perdon gente buena suerte con el tp

2022-10-16 23:37 UTC, tfloxolodeiro commented
hola volvi gente resulta que la carrera de veterinaria no me da tanta plata como sistemas asi que volvi vamos para adelante 🦾

2022-10-17 00:00 UTC, Lautarourtiaga commented
@tfloxolodeiro vos no eras peronista ? Recuerdo que una vez dijiste eso de tu abuelo que evita le dio la casa e ibas a las marchas. Si vas a veterinaria estaría bueno que no influencies a los perritos y a los gatitos con esas ideas. Siempre esta bueno que la postura politica de las mascotas no esté influenciada por sus veterinarios.

Mira no digo que ser peronista sea malo, solo digo, no influencies, ser veterinario no tiene nada que ver con la politica. Por favor respeta eso. El bichito no tiene la culpa

![image](https://user-images.githubusercontent.com/34402401/196065140-a8a5deae-43ac-485f-b585-28b03b23e26a.png)

2022-10-17 00:31 UTC, tfloxolodeiro commented
'''''''''''''''''''''''''''

2022-10-17 21:46 UTC, tfloxolodeiro commented
hola buen dia amigos hoy voy a ver el segundo capitulo de utena!

2022-10-17 22:31 UTC, merged